<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQe1iryb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQe1iryb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQe1iryb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQe1iryb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQe1iryb\appProdProjectContainer([
    'container.build_hash' => 'Qe1iryb',
    'container.build_id' => '57de4827',
    'container.build_time' => 1562845797,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQe1iryb');
