sonde_homepage:
    path:     /
    defaults: { _controller: SondeBundle:Default:index }

sonde_by_sector:
    path: /sonde_sector
    defaults: { _controller: SondeBundle:Default:getSondeBySector }
    methods: [POST]

sonde_details:
    path: /sonde_details/{sondaId}
    defaults: { _controller: SondeBundle:Default:sondeDetails }

sonde_charts:
    path: /sonde_charts/{sondaId}
    defaults: { _controller: SondeBundle:Default:sondeCharts }

sonde_debit:
    path: /sonde_debit/{sondaId}
    defaults: { _controller: SondeBundle:Default:sondeDebit }
